baseURL = "https://isfegu.netlify.app/"
title = "Aprendiz de todo, oficial de nada"
languageCode = "es-es"
theme = "hyde"
enableGitInfo = "true"

[params]
  description = "Apuntes que me fuerzo a escribir para tratar de entender mejor."