[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/flexbox-markdown-bash-blog/"
  to = "/"
  status = 410

[[redirects]]
  from = "/paleta-colores-nord-ilustraciones-svg-gratis/"
  to = "/"
  status = 410

  [[redirects]]
  from = "/dotyyphen-dohy-ascii-morse-rust/"
  to = "/dothyphen-dohy-ascii-morse-rust/"
  status = 301

  [[redirects]]
  from = "/dotyyphen-ascii-morse-rust-webassembly-wasi/"
  to = "/dothyphen-ascii-morse-rust-webassembly-wasi/"
  status = 301