name = "Anedonia"
license = "CC BY-NC 4.0"
licenselink = "https://github.com/isfegu/anedonia.website/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog"]
features = ["blog", "themes"]
min_version = 0.53

[author]
    name = "isfegu"
    homepage = "https://anedonia.website"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
