# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/v0.187.0/containers/go/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/vscode/devcontainers/go

# Install Hugo
RUN apt update && apt install -y hugo