# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/python-3/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/vscode/devcontainers/go

# Install Hugo
RUN apt update && apt install -y hugo